### ISSUE TITLE
Non API REST handler

### ISSUE THREAD

**Issue by sirgalleto** [jonathan-casarrubias/loopback-component-pubsub#13] opened 2016-09-12 22:21 UTC
If I create a object into a custom model without the api rest the pubsub not handle the event.

**Comment by jonathan-casarrubias** [comment] 2016-09-13 02:04
Hi @sirgalleto the pubsub only works for remote methods, this means it should be associated to the rest module of loopback, in other words if it is not a remoteMethod it won't be handled.

I believe this is duplicated: https://github.com/mean-expert-official/loopback-component-pubsub/issues/10

unless you describe a different use case, I will be closing this in favour of #10 

Cheers
Jon

**Closed as completed by jonathan-casarrubias** 2016-09-13 02:04 UTC

**Comment by sirgalleto** [comment] 2016-09-13 04:23
Oh, then I need create a http petition into the my loopback logic? So do you know any way to get a master token or anything like that?

**Comment by sirgalleto** [comment] 2016-09-13 16:01
@jonathan-casarrubias So this component could handle custom remote methods?

**Comment by jonathan-casarrubias** [comment] 2016-09-13 17:53
@sirgalleto currently can work with custom remote methods, only if these are post or put methods but not get.

The limitation right now is that If you would like to subscribe to events, it needs to be called from a the REST interface, so the remoteHook is executed.

The new module I'm working on will allow you to send custom messages regardless the REST Interface.

Cheers
Jon

**Comment by sirgalleto** [comment] 2016-09-13 18:27
Yes but, the sdk does not build the custom remote methods events, or how can I configure it?

**Comment by jonathan-casarrubias** [comment] 2016-09-13 20:03
@sirgalleto the SDK Builder does create listeners for custom remoteMethods, the only rule is that you define the http method as POST or PUT.

if you click [here](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/common/models/room.js) you will see in the test application, there is a greetPost method defined.

and if you click [here](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/src/app/shared/sdk/services/custom/Room.ts#L2209) you will see the method is generated for that one but not for greetGet.

**Comment by sirgalleto** [comment] 2016-09-13 20:22
But if the method is called by GET  (external system requirements) can I generate a watcher for that?

**Comment by jonathan-casarrubias** [comment] 2016-09-13 20:38
You can not while using the publish-subscribe pattern... events will be emitted only at the moment you publish something, therefore is needed a put or post.

If we forget about the pub-sub, currently and alternatively the SDK Builder also provides with another type of real-time communication using Server Sent Events which is already built-in with LoopBack (change-stream), the problem is that events are also fired when there is a model modification, for example: create, update, remove.

The third method of real-time communication I'm currently implementing; will be more flexible and will allow you to send custom messages at any moment at any place, so in that case you will be able to add a remoteHook for your GET Endpoint and send a message from there.

The first two approaches do follow a pattern and will not be modified, so for now you will need to keep an eye on the third implementation until is released. I estimate no more than 2 weeks

Cheers
Jon

**Comment by sirgalleto** [comment] 2016-09-13 20:42
Ohh sounds very good. When do you plan to release that?.

So I'm thinking in send me a POST petition backend to backend, but I need an authorization. Very thanks Jon.
